version: '3.8'
services:
  db:
    container_name: postgresDB
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filemanagement
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresqldb
volumes:
  db:
    driver: local